// Generated by CoffeeScript 1.10.0
var GameScene, config, engine,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

config = Config.get();

config.fillWindow();

engine = new Engine3D();

GameScene = (function(superClass) {
  extend(GameScene, superClass);

  function GameScene() {
    return GameScene.__super__.constructor.apply(this, arguments);
  }

  GameScene.prototype.init = function(options) {};

  GameScene.prototype.tick = function(tpf) {};

  GameScene.prototype.doKeyboardEvent = function(event) {};

  GameScene.prototype.doMouseEvent = function(event, raycaster) {};

  return GameScene;

})(BaseScene);

Engine3D.scenify(engine, function() {});

engine.render();
